### ISSUE TITLE
implement ftp server with docker

### ISSUE THREAD

**Issue by picatz** [picatz/goldengirl#18]
There's no offical centos example to pull reference from, but there's this:
https://github.com/fauria/docker-vsftpd

**Comment by reno777** [comment]
So this needs sftp and ftp, as well as up and down on both correct?

**Comment by picatz** [comment]
The scoring engine check apparently is the same. Yolo

**Comment by reno777** [comment]
Docker file is present, and same with the .conf file. I ran into a problem with getting systemctl to run within docker. I have found a potential fix, but I need to go to bed lmao.

**Comment by reno777** [comment]
Didnt mean to close lol oops

**Comment by picatz** [comment]
@reno777 Yeah you can't run systemd services within docker basically. You should run them directly.

**Comment by picatz** [comment]
🤔 https://github.com/andrewarrow/paradise_ftp

**Comment by picatz** [comment]
@reno777 https://github.com/fclairamb/ftpserver 👌

**Comment by picatz** [comment]
```shell
# Creating a storage dir
mkdir data

# Starting the sample FTP server
docker run --rm -d -p 2121-2200:2121-2200 -v $(pwd)/data:/data fclairamb/ftpserver

# Connecting to it and uploading a file
ftp ftp://test:test@localhost:2121
!wget -c -O ftpserver-v0.3 https://github.com/fclairamb/ftpserver/releases/download/v0.3/ftpserver
put ftpserver-v0.3 ftpserver-v0.3
quit
ls -lh data/ftpserver-v0.3
```

**Comment by picatz** [comment]
Fixed with https://github.com/picatz/goldengirl/commit/c8d99d65fdd8347d496ef51bc68bd2dc6315b485
