### ISSUE TITLE
test postgresql dockerfile

### ISSUE THREAD

**Issue by picatz** [picatz/goldengirl#29]

**Comment by malwaremily** [comment]
#  Postgresql Test : PASSED
### Command History
`cd ~/dockerfiles/postgresql`
`sudo docker build -t postgresql .`
`sudo docker run -itd -p 5432:5432 postgresql`
`psql -h 127.0.0.1 -U picat`
password: picat
CTRL+Z to escape
`sudo docker ps -a`
`sudo docker logs$CONTAINERID`
### Test Details
Last Run:  1/28/18 21:32
### Photo Log
Build.
![build](https://user-images.githubusercontent.com/33560517/35491302-a7b6d56a-0473-11e8-9b03-54d6bc37a1af.PNG)
Run. Login. Verify. Logs.
![run](https://user-images.githubusercontent.com/33560517/35491303-ab0e61a6-0473-11e8-9866-95dd2a767447.PNG)

**Comment by picatz** [comment]
👍
