### ISSUE TITLE
test mysql dockerfile

### ISSUE THREAD

**Issue by picatz** [picatz/goldengirl#30]

**Comment by malwaremily** [comment]
# mysql Test : Passed
### Command History
    `cd ~/dockerfiles/mysql`
    `sudo docker build -t mysql . `
    `sudo docker run -itd -p 3306:3306 mysql`
    `mysql -h 127.0.0.1 -u root -p`
    password: picat
    CTRL+Z to escape
    `sudo docker ps -a`
    `sudo docker logs `$CONTAINERID

### photo log
Build.
![build](https://user-images.githubusercontent.com/33560517/35491123-8c902fee-0472-11e8-9808-f4c5e0a5ee9e.PNG)
Run. Login. Verify. Logs.
![run](https://user-images.githubusercontent.com/33560517/35491125-91583e22-0472-11e8-8edb-0f4fbe894f4f.PNG)





## test details
last ran: 1/28/18 21:32

**Comment by picatz** [comment]
👍
