### ISSUE TITLE
test ssh server

### ISSUE THREAD

**Issue by picatz** [picatz/goldengirl#35]
Test ssh server implemented with https://github.com/picatz/goldengirl/commit/f87ea8ed6eaa5e1975d140e87c9a0ed87067d98a

**Comment by malwaremily** [comment]
# SSH Test : PASSED
### Command History
    `cd ~/dockerfiles/ssh`
    `sudo docker build -t ssh .`
    `sudo docker run -itd -p 2222:22 ssh`
    `sudo docker ps -a`
    `sudo docker logs `$CONTAINERID

### Photo Log
Build SSH docker container.
![build](https://user-images.githubusercontent.com/33560517/35493242-b720f740-047f-11e8-8018-5d333bc0ab77.PNG)
Run SSH container, verify its running, no logs present.
![runverify](https://user-images.githubusercontent.com/33560517/35493273-fe4b508e-047f-11e8-8512-cec3eb3fdf4b.PNG)

### Test Details
Last Run:  1/28/18 23:04

**Comment by picatz** [comment]
👍
