### ISSUE TITLE
test ftp dockerfiles

### ISSUE THREAD

**Issue by malwaremily** [picatz/goldengirl#36]
#  Test ftp : PASS
### Command History

    cd ~/dockerfiles/ftp
    sudo docker build -t ftp .
    sudo docker run -itd -p 21:21 ftp
    sudo python test.py 0.0.0.0 21 root picat /example wiggle
    sudo docker ps -a
    sudo docker logs $CONTAINERID

### Test Details
Last Run: 1/28/18 3:07
Dockerfiles: https://github.com/picatz/goldengirl/tree/master/dockerfiles/ftp

### Photo Logs
Build the container.
![build](https://user-images.githubusercontent.com/33560517/35493397-e7425396-0480-11e8-9f0c-31b9a0d54b42.PNG)
Run. Login. Get a file. Logout. Verify. View Logs.
![runverify](https://user-images.githubusercontent.com/33560517/35493398-e97ea312-0480-11e8-8563-97a64981fc27.PNG)

**Comment by picatz** [comment]
👍
