### ISSUE TITLE
test dns

### ISSUE THREAD

**Issue by malwaremily** [picatz/goldengirl#37]
#  Test DNS: PASS
### Command History
    cd ~/dockerfiles/dns
    go get github.com/miekg/dns
    go build dns.go
    sudo docker build -t dns .
    sudo docker run -itd -p 53:5353/udp dns
    dig @localhost test.service
    sudo docker ps -a
    sudo docker logs $CONTAINERID

### Test Details
Last Run: 1/28/18 23:19
Dockerfiles: https://github.com/picatz/goldengirl/tree/master/dockerfiles/dns
### Photo Logs
Build.
![build](https://user-images.githubusercontent.com/33560517/35493497-dd0229be-0481-11e8-9ca8-4b58e1fac1f0.PNG)

Run. Verify. Logs.
![run](https://user-images.githubusercontent.com/33560517/35493519-0b7806ba-0482-11e8-97bd-2d3ff898dc30.PNG)

**Comment by picatz** [comment]
👍
