### ISSUE TITLE
test elasticsearch

### ISSUE THREAD

**Issue by malwaremily** [picatz/goldengirl#38]
#  Test elasticsearch: PASS
### Command History
    cd ~/dockerfiles/elasticsearch
    sudo docker build -t elasticsearch .
    sudo docker run -itd -p 9200:9200 elasticsearch
    curl http://localhost:9200
    sudo docker ps -a
    sudo docker logs $CONTAINERID
### Test Details
Last Run: 1/28/18 4:01
Dockerfiles: https://github.com/picatz/goldengirl/tree/master/dockerfiles/elasticsearch
### Photo Logs
Build.
![build](https://user-images.githubusercontent.com/33560517/35493677-20f26dc2-0483-11e8-86ec-6c26c8147e72.PNG)

Run. Test. Verify. Logs.
![run](https://user-images.githubusercontent.com/33560517/35493679-24316114-0483-11e8-8836-cda8e7259d0b.PNG)

**Comment by picatz** [comment]
👍
